### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by HerbM** [npcardoso/chessocr#3]
Looks like a nice attempt that was nearing success, but incomplete (piece detection, error correction...)

I don't think I have the skillset to quickly finish it.

Any chance it will proceed or do you know of anyone else working on it?

**Comment by npcardoso** [comment]
Hey! Thank you for the interest in this project.

In the past I started working on the piece detection part and what I did was to run the script against a large set of chess book pages and extract all the tiles. It worked relatively well but I stopped there.

My idea was to use ML to first distinguish empty tiles from piece tiles. After that I would move on to detect the piece type.
To that end I thought of using clustering algorithms to try to group the extracted tiles onto several groups. If the generated groups were accurate I would use them as a training set to some classifier algorithm. If the groups were not reliable, I would have to resort to manually create the groups.
Also, I think it would be useful to separate piece detection from color detection, i.e., normalize the piece color so white and black pieces would look alike and use some other way of detecting piece color.

As for error correction, I thought of using a chess game database to help breaking ties in the case some piece classification has several candidates with similar scores


Unfortunately, for the time being, I don't have the time to work in this project but I would be glad if someone else would be willing to contribute.

**Comment by HerbM** [comment]
That's too bad, and it would make a good 1st project (for me) if I had the time.

I'm surprised that no one seems to have done this.  There are several working versions for Android.

It's only a little tedious to dig out my phone and take a picture of the screen then send the FEN to my PC (I usually transfer through Discord as a messaging app from Phone to PC.)

I use ChessVision.ai (free, and it's basically VERY LOW key advertisement to sell their web service for doing entire books) and apparently it has a recognize from local images but that would involve making a screen shot or otherwise exporting the pictures when reading a book which seem even more tedious on Anroid than a PC.

Mostly I read on my pad (or PC) and use my phone to take pictures and analyze book positions or send to PC.

It works; it's not perfect; and I supposed I could buy the web service if I wanted to entire books at once -- it's not expensive IIRC
